language: rust

rust:
- stable
- beta
- nightly

cache:
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"

script:
- cargo build
- cargo build --features thread_safe

os:
- linux
- osx

notifications:
  email:
    on_success: never

branches:
  only:
  - master

after_success: |-
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_OS_NAME = linux ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo rust_cast | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
