[package]
name = "rust_cast"
description = "Library that allows you to communicate with Google Cast enabled devices (e.g. Chromecast)."
documentation = "https://azasypkin.github.io/rust-cast/"
homepage = "https://github.com/azasypkin/rust-cast"
repository = "https://github.com/azasypkin/rust-cast"
readme = "README.md"
license = "MIT"
keywords = ["cast", "chromecast", "google"]
version = "0.15.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
categories = ["api-bindings", "hardware-support", "multimedia"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
log = "0.4.8"
openssl = "0.10.26"
protobuf = "=2.10.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"

[build-dependencies]
protoc-rust = "=2.10.0"
